import * as fs from "fs";
import { Base64 } from "js-base64";
import * as path from "path";
import { grammarFiles } from "tmt/constants/languages";

(() => {
    if (!fs.existsSync("./src/languages/")) {
        fs.mkdirSync("./src/languages/", { recursive: true });
    }

    const generateTextmateGrammar = (name: string, file: string) => {
        const grammar = Base64.encode(fs.readFileSync(file).toString());
        fs.writeFileSync(
            `./src/languages/${path.basename(file)}.ts`,
            [
                "/* eslint-disable */",
                "/* THIS FILE IS AUTOMATICALLY GENERATED, DO NOT EDIT */",
                'import { Base64 } from "js-base64";',
                "",
                `export const ${name}TextmateGrammar = Base64.decode(String.raw\``,
                grammar.trim(),
                `\`);`,
            ].join("\n")
        );
    };

    grammarFiles.forEach(([name, file]) => generateTextmateGrammar(name, file));
})();
